services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    hostname: db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - microp
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/:ro
      - pgdata:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: "mypguser"
      POSTGRES_PASSWORD: "mypgpass"
  microp:
    image: microp
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    expose:
     - "8086"
    ports:
      - "8086:8086"
    networks:
     - microp
    environment:
      DB_USER: "mypguser"
      DB_PASS: "mypgpass"
      DB_DATABASE: "mypguser"
      DB_PORT: "5432"
      DB_HOST: "db"
  haproxy:
    image: haproxy
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    networks:
      - microp
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./config/microp.pem:/usr/local/etc/haproxy/microp.pem:ro
networks:
  microp:
    driver: bridge

volumes:
  pgdata: